version: '3.8'
services:
    db:
      image: postgres:16.3
      container_name: ShireStore
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
      volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./db:/var/lib/postgresql/dbdata
    pgadmin:
      image: dpage/pgadmin4:8.4
      container_name: ShireStoreManager
      restart: always
      ports:
        - "8888:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL
        - PGADMIN_DEFAULT_PASSWORD
      volumes:
        - ./pgadmin:/var/lib/pgadmin
volumes:
    db_volume:
    pgadmin_volume:
